include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  errors:
    # Allow for demos and examples
    avoid_print: ignore
    
linter:
  rules:
    # Additional rules on top of flutter_lints
    - always_declare_return_types
    - avoid_void_async
    - directives_ordering
    - prefer_single_quotes
    - sort_constructors_first
    - sort_unnamed_constructors_first
    - unnecessary_lambdas
    - use_super_parameters