name: rough
description: Rough is a library that allows you draw in a sketchy, hand-drawn-like style
version: 2.0.0
homepage: https://github.com/sergiandreplace/flutter_rough
repository: https://github.com/sergiandreplace/flutter_rough

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
