name: rough_flutter
description: A Flutter library for sketchy, hand-drawn-style graphics. Maintained fork and migration of the original rough package with Dart 3, null safety, and web/mobile optimizations.
version: 0.1.2
homepage: https://github.com/acyment/flutter_rough
repository: https://github.com/acyment/flutter_rough

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
