name: rough_flutter
description: A Flutter library that allows you to draw in a sketchy, hand-drawn-like style. Forked and maintained version of the original rough package.
version: 2.0.0
homepage: https://github.com/acyment/flutter_rough
repository: https://github.com/acyment/flutter_rough

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
