name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: stable
        channel: stable
    
    - name: Check for version bump
      run: |
        git fetch origin master
        OLD_VERSION=$(git show origin/master:pubspec.yaml | grep "^version:" | cut -d' ' -f2)
        NEW_VERSION=$(grep "^version:" pubspec.yaml | cut -d' ' -f2)
        if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
          echo "::warning::Version number hasn't been updated"
        fi
    
    - name: Check CHANGELOG
      run: |
        if ! git diff --name-only origin/master..HEAD | grep -q "CHANGELOG.md"; then
          echo "::warning::CHANGELOG.md hasn't been updated"
        fi
    
    - name: Lint PR title
      uses: amannn/action-semantic-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}